// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: UI_tutorial

#ifndef _UI_TUTORIAL_UI_H
#define _UI_TUTORIAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ConsumptionLabel;
extern lv_obj_t * ui_EfficiencyLabel;
extern lv_obj_t * ui_rpmLabel;
extern lv_obj_t * ui_laptimeLabel;
extern lv_obj_t * ui_fullattemptLabel;
extern lv_obj_t * ui_lapsLabel;
extern lv_obj_t * ui_velocityLabel;
extern lv_obj_t * ui_messageLabel;
extern lv_obj_t * ui_Arc1;
void ui_event_Button1_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_batEmpty;
extern lv_obj_t * ui_batFull;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui____initial_actions0;

extern button_aux;

LV_IMG_DECLARE(ui_img_1353450204);    // assets/bg-ui-tutorial.png
LV_IMG_DECLARE(ui_img_670504427);    // assets/reset-button.png
LV_IMG_DECLARE(ui_img_2092287828);    // assets/battery-empty.png
LV_IMG_DECLARE(ui_img_53718616);    // assets/battery-full.png



LV_FONT_DECLARE(ui_font_Open_Sans_SemiBold_26);
LV_FONT_DECLARE(ui_font_Open_Sans_SemiBold_24);
LV_FONT_DECLARE(ui_font_Open_Sans_ExtraBold_46);
LV_FONT_DECLARE(ui_font_Open_Sans_ExtraBold_26);
LV_FONT_DECLARE(ui_font_Open_Sans_ExtraBold_32);
LV_FONT_DECLARE(ui_font_Open_Sans_ExtraBold_72);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
