// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: UI_tutorial

#include "ui.h"

lv_chart_series_t * ui_Chart1_series_1 = NULL;
lv_chart_series_t * ui_Chart1_series_2 = NULL;

lv_coord_t ui_Chart1_series_1_array[60] = {0};
lv_coord_t ui_Chart1_series_2_array[60] = {0};

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_1353450204, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsumptionLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ConsumptionLabel, 90);
    lv_obj_set_height(ui_ConsumptionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConsumptionLabel, -180);
    lv_obj_set_y(ui_ConsumptionLabel, 132);
    lv_obj_set_align(ui_ConsumptionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConsumptionLabel, "000.00");
    lv_obj_set_style_text_color(ui_ConsumptionLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsumptionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConsumptionLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsumptionLabel, &ui_font_Open_Sans_SemiBold_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EfficiencyLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_EfficiencyLabel, 90);
    lv_obj_set_height(ui_EfficiencyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EfficiencyLabel, -178);
    lv_obj_set_y(ui_EfficiencyLabel, 169);
    lv_obj_set_align(ui_EfficiencyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EfficiencyLabel, "000.00");
    lv_obj_set_style_text_color(ui_EfficiencyLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EfficiencyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EfficiencyLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EfficiencyLabel, &ui_font_Open_Sans_SemiBold_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpmLabel, 124);
    lv_obj_set_height(ui_rpmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmLabel, -208);
    lv_obj_set_y(ui_rpmLabel, 58);
    lv_obj_set_align(ui_rpmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmLabel, "000 rpm");
    lv_obj_set_style_text_color(ui_rpmLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rpmLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmLabel, &ui_font_Open_Sans_SemiBold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laptimeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_laptimeLabel, 207);
    lv_obj_set_height(ui_laptimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laptimeLabel, 236);
    lv_obj_set_y(ui_laptimeLabel, -160);
    lv_obj_set_align(ui_laptimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laptimeLabel, "00:00.00");
    lv_obj_set_style_text_color(ui_laptimeLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_laptimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_laptimeLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laptimeLabel, &ui_font_Open_Sans_ExtraBold_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fullattemptLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_fullattemptLabel, 207);
    lv_obj_set_height(ui_fullattemptLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fullattemptLabel, 237);
    lv_obj_set_y(ui_fullattemptLabel, -103);
    lv_obj_set_align(ui_fullattemptLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fullattemptLabel, "00:00.00");
    lv_obj_set_style_text_color(ui_fullattemptLabel, lv_color_hex(0xA2A3A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fullattemptLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fullattemptLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fullattemptLabel, &ui_font_Open_Sans_ExtraBold_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lapsLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lapsLabel, 58);
    lv_obj_set_height(ui_lapsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lapsLabel, 178);
    lv_obj_set_y(ui_lapsLabel, -84);
    lv_obj_set_align(ui_lapsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lapsLabel, "00");
    lv_obj_set_style_text_color(ui_lapsLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lapsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lapsLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lapsLabel, &ui_font_Open_Sans_ExtraBold_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_velocityLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_velocityLabel, 160);
    lv_obj_set_height(ui_velocityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_velocityLabel, -209);
    lv_obj_set_y(ui_velocityLabel, 163);
    lv_obj_set_align(ui_velocityLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_velocityLabel, "00.0");
    lv_obj_set_style_text_color(ui_velocityLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_velocityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_velocityLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_velocityLabel, &ui_font_Open_Sans_ExtraBold_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_messageLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_messageLabel, 322);
    lv_obj_set_height(ui_messageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_messageLabel, 181);
    lv_obj_set_y(ui_messageLabel, 12);
    lv_obj_set_align(ui_messageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_messageLabel, "Lorem ipsum dolor sit amet, consectetur");
    lv_obj_set_style_text_color(ui_messageLabel, lv_color_hex(0xD4D3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_messageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_messageLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_messageLabel, &ui_font_Open_Sans_SemiBold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 300);
    lv_obj_set_height(ui_Arc1, 300);
    lv_obj_set_x(ui_Arc1, -200);
    lv_obj_set_y(ui_Arc1, -31);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 99);
    lv_arc_set_value(ui_Arc1, 50);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x323A4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Arc1, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x003AFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Arc1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Button1 = ui_Button1_create(ui_Screen1);
    lv_obj_set_x(ui_Button1, 59);
    lv_obj_set_y(ui_Button1, -117);

    ui_batEmpty = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_batEmpty, &ui_img_2092287828);
    lv_obj_set_width(ui_batEmpty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batEmpty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batEmpty, 313);
    lv_obj_set_y(ui_batEmpty, 149);
    lv_obj_set_align(ui_batEmpty, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batEmpty, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batEmpty, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_batEmpty, 200);

    ui_batFull = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_batFull, &ui_img_53718616);
    lv_obj_set_width(ui_batFull, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batFull, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batFull, 313);
    lv_obj_set_y(ui_batFull, 149);
    lv_obj_set_align(ui_batFull, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batFull, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batFull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_batFull, 200);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 200);
    lv_obj_set_height(ui_Chart1, 78);
    lv_obj_set_x(ui_Chart1, 137);
    lv_obj_set_y(ui_Chart1, 141);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 60);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 120);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 280);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 15, 3, 6, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 2, 2, true, 10);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 2, 0, 3, 2, true, 10);
    ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFFBA00),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x40CC25),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1_Button1, LV_EVENT_ALL, NULL);
}